name: build
on:
  push:
    branches: ['series/1.x', 'series/2.x']
  pull_request:
    branches: ['series/1.x', 'series/2.x']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [2.13.x]
        java-version: [8, 11, 17, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - name: Run tests
        run: sbt ++${{ matrix.scala-version }} clean test
